export const shelters = [
    {
      id: 1,
      phoneNumber: "+1(123)456-7890",
      location: {
        addressLine1: "123 Main Street",
        addressLine2: "Suite 100",
        city: "Anytown",
        state: "CA",
        zipcode: "90210",
      },
      name: "Pawsome Shelter",
    },
    {
      id: 2,
      phoneNumber: "+1(234)567-8901",
      location: {
        addressLine1: "456 Oak Avenue",
        addressLine2: "Unit B",
        city: "Smallville",
        state: "NY",
        zipcode: "54321",
      },
      name: "Furry Friends Rescue",
    },
    {
      id: 3,
      phoneNumber: "+1(345)678-9012",
      location: {
        addressLine1: "789 Maple Drive",
        addressLine2: "Apt 202",
        city: "Sunnydale",
        state: "FL",
        zipcode: "12345",
      },
      name: "Safe Haven Animal Shelter",
    },
    {
      id: 4,
      phoneNumber: "+1(456)789-0123",
      location: {
        addressLine1: "101 Pine Street",
        addressLine2: "Floor 3",
        city: "Riverdale",
        state: "GA",
        zipcode: "67890",
      },
      name: "Compassionate Critters Center",
    },
    {
      id: 5,
      phoneNumber: "+1(567)890-1234",
      location: {
        addressLine1: "246 Elm Road",
        addressLine2: "",
        city: "Hilltop",
        state: "TX",
        zipcode: "54321",
      },
      name: "Whisker Haven Rescue",
    },
    {
      id: 6,
      phoneNumber: "+1(678)901-2345",
      location: {
        addressLine1: "777 Pineapple Avenue",
        addressLine2: "Suite 50",
        city: "Seaside",
        state: "CA",
        zipcode: "98765",
      },
      name: "Ocean Paws Shelter",
    },
    {
      id: 7,
      phoneNumber: "+1(789)012-3456",
      location: {
        addressLine1: "321 Cherry Lane",
        addressLine2: "Unit C",
        city: "Springfield",
        state: "IL",
        zipcode: "54321",
      },
      name: "Happy Tails Animal Rescue",
    },
    {
      id: 8,
      phoneNumber: "+1(890)123-4567",
      location: {
        addressLine1: "555 Willow Street",
        addressLine2: "Apt 303",
        city: "Meadowville",
        state: "OH",
        zipcode: "34567",
      },
      name: "Loving Hearts Pet Sanctuary",
    },
    {
      id: 9,
      phoneNumber: "+1(901)234-5678",
      location: {
        addressLine1: "999 Oakwood Drive",
        addressLine2: "",
        city: "Clearwater",
        state: "FL",
        zipcode: "54321",
      },
      name: "Sunshine Animal Haven",
    },
    {
      id: 10,
      phoneNumber: "+1(012)345-6789",
      location: {
        addressLine1: "777 Maple Avenue",
        addressLine2: "Suite 25",
        city: "Evergreen",
        state: "CO",
        zipcode: "12345",
      },
      name: "Mountain Paws Rescue",
    },
    {
      id: 11,
      phoneNumber: "+1(123)456-7890",
      location: {
        addressLine1: "456 Elm Street",
        addressLine2: "Floor 2",
        city: "Rockville",
        state: "MD",
        zipcode: "87654",
      },
      name: "Forever Friends Shelter",
    },
    {
      id: 12,
      phoneNumber: "+1(234)567-8901",
      location: {
        addressLine1: "888 Cedar Lane",
        addressLine2: "Unit 10",
        city: "Rosewood",
        state: "WA",
        zipcode: "54321",
      },
      name: "Caring Critters Rescue",
    },
    {
      id: 13,
      phoneNumber: "+1(345)678-9012",
      location: {
        addressLine1: "111 Pinecone Road",
        addressLine2: "",
        city: "Greenfield",
        state: "MT",
        zipcode: "45678",
      },
      name: "Pine Ridge Pet Sanctuary",
    },
    {
      id: 14,
      phoneNumber: "+1(456)789-0123",
      location: {
        addressLine1: "222 Cedarwood Drive",
        addressLine2: "Suite 5",
        city: "Mapleton",
        state: "PA",
        zipcode: "54321",
      },
      name: "Wagging Tails Shelter",
    },
    {
      id: 15,
      phoneNumber: "+1(567)890-1234",
      location: {
        addressLine1: "999 Magnolia Lane",
        addressLine2: "Apt 101",
        city: "Sunrise",
        state: "FL",
        zipcode: "34567",
      },
      name: "Sunrise Pet Refuge",
    },
    {
      id: 16,
      phoneNumber: "+1(678)901-2345",
      location: {
        addressLine1: "444 Pine Street",
        addressLine2: "Suite 30",
        city: "Hillcrest",
        state: "CA",
        zipcode: "65432",
      },
      name: "Paws & Claws Adoption Center",
    },
    {
      id: 17,
      phoneNumber: "+1(789)012-3456",
      location: {
        addressLine1: "777 Elmwood Drive",
        addressLine2: "",
        city: "Silverton",
        state: "OR",
        zipcode: "54321",
      },
      name: "Silver Paws Animal Rescue",
    },
    {
      id: 18,
      phoneNumber: "+1(890)123-4567",
      location: {
        addressLine1: "123 Birch Lane",
        addressLine2: "Unit 15",
        city: "Lakeside",
        state: "MI",
        zipcode: "45678",
      },
      name: "Lakeside Love & Care Shelter",
    },
    {
      id: 19,
      phoneNumber: "+1(901)234-5678",
      location: {
        addressLine1: "555 Oak Avenue",
        addressLine2: "Floor 4",
        city: "Pinecrest",
        state: "NC",
        zipcode: "54321",
      },
      name: "Pinecrest Pet Haven",
    },
    {
      id: 20,
      phoneNumber: "+1(012)345-6789",
      location: {
        addressLine1: "999 Cedarwood Lane",
        addressLine2: "Suite 20",
        city: "Willow Creek",
        state: "WA",
        zipcode: "34567",
      },
      name: "Willow Creek Animal Sanctuary",
    },
  ];
  